apiVersion: v1
kind: Secret
metadata:
  name: postgresql
data:
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  REPMGR_PASSWORD: cG9zdGdyZXMxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpool
data:
  PGPOOL_ADMIN_PASSWORD: cG9zdGdyZXMxMjM=
  PGPOOL_POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  PGPOOL_SR_CHECK_PASSWORD: cG9zdGdyZXMxMjM=
